framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: true

    session:
        handler_id: ~

    php_errors:
        log: true

    cache:
        prefix_seed: jeboehm/mailserver-admin
