security:
    providers:
        mail:
            id: App\Security\Provider\UserProvider

    encoders:
        App\Entity\User:
            id: App\Security\Encoder\DefaultPasswordEncoder

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: false
            http_basic: true

    access_control:
        - { path: ^/, roles: ROLE_ADMIN }
